/obj/machinery/vending/wardrobe/cargo_wardrobe
	products_ff = list(
		/obj/item/clothing/under/costume/playbunny/cargo_bunnysuit = 3,
		/obj/item/clothing/under/costume/playbunny/miner/bunnysuit = 3,
		/obj/item/clothing/under/rank/cargo/mailman_bunnysuit = 3,
		/obj/item/clothing/under/costume/playbunny/bitrunner = 3,
		/obj/item/clothing/suit/jacket/tailcoat/cargo = 3,
		/obj/item/clothing/suit/jacket/tailcoat/miner = 3,
		/obj/item/clothing/suit/jacket/tailcoat/bitrunner = 3,
		/obj/item/clothing/neck/playbunny/cargo = 3,
		/obj/item/clothing/neck/playbunny/miner = 3,
		/obj/item/clothing/neck/playbunny/mailman = 3,
		/obj/item/clothing/neck/playbunny/bitrunner = 3,
		/obj/item/clothing/head/playbunny/cargo = 3,
		/obj/item/clothing/head/playbunny/miner = 3,
		/obj/item/clothing/head/playbunny/mailman = 3,
		/obj/item/clothing/head/playbunny/bitrunner = 3,
		/obj/item/clothing/shoes/workboots/mining/heeled = 3,
		/obj/item/clothing/shoes/fancy_heels/brown = 3,
		/obj/item/clothing/shoes/fancy_heels/orange = 3,
	)
