/obj/machinery/vending/wardrobe/cargo_wardrobe
	products_ff = list(
		/obj/item/clothing/under/costume/playbunny/cargo = 3,
		/obj/item/clothing/under/costume/playbunny/miner = 3,
		/obj/item/clothing/under/costume/playbunny/mailman = 3,
		/obj/item/clothing/under/costume/playbunny/bitrunner = 3,
		/obj/item/clothing/suit/jacket/playbunny/cargo = 3,
		/obj/item/clothing/suit/jacket/playbunny/miner = 3,
		/obj/item/clothing/suit/jacket/playbunny/bitrunner = 3,
		/obj/item/clothing/neck/playbunny/tie/cargo = 3,
		/obj/item/clothing/neck/playbunny/tie/miner = 3,
		/obj/item/clothing/neck/playbunny/tie/mailman = 3,
		/obj/item/clothing/neck/playbunny/tie/bitrunner = 3,
		/obj/item/clothing/head/playbunny/cargo = 3,
		/obj/item/clothing/head/playbunny/miner = 3,
		/obj/item/clothing/head/playbunny/mailman = 3,
		/obj/item/clothing/head/playbunny/bitrunner = 3,
		/obj/item/clothing/shoes/workboots/mining/heeled = 3,
		/obj/item/clothing/shoes/fancy_heels/brown = 3,
		/obj/item/clothing/shoes/fancy_heels/orange = 3,
	)
