/obj/machinery/vending/wardrobe/law_wardrobe
	products_ff = list(
		/obj/item/clothing/under/costume/playbunny/curator_black = 3,
		/obj/item/clothing/under/costume/playbunny/curator_blue = 3,
		/obj/item/clothing/under/costume/playbunny/curator_red = 3,
		/obj/item/clothing/under/costume/playbunny/lawyer_good = 3,
		/obj/item/clothing/suit/jacket/tailcoat/lawyer_black = 3,
		/obj/item/clothing/suit/jacket/tailcoat/lawyer_blue = 3,
		/obj/item/clothing/suit/jacket/tailcoat/lawyer_red = 3,
		/obj/item/clothing/suit/jacket/tailcoat/lawyer_good = 3,
		/obj/item/clothing/neck/playbunny/lawyer_black = 3,
		/obj/item/clothing/neck/playbunny/lawyer_blue = 3,
		/obj/item/clothing/neck/playbunny/lawyer_red = 3,
		/obj/item/clothing/neck/playbunny/lawyer_good = 3,
		/obj/item/clothing/head/playbunny/lawyer_black = 3,
		/obj/item/clothing/head/playbunny/lawyer_blue = 3,
		/obj/item/clothing/head/playbunny/lawyer_red = 3,
		/obj/item/clothing/head/playbunny/lawyer_good = 3,
		/obj/item/clothing/shoes/fancy_heels/black = 3,
		/obj/item/clothing/shoes/fancy_heels/blue = 3,
		/obj/item/clothing/shoes/fancy_heels/red = 3,
	)
