/obj/machinery/vending/wardrobe/sec_wardrobe
	products_ff = list(
		/obj/item/clothing/under/costume/playbunny/security = 3,
		/obj/item/clothing/under/costume/playbunny/security_assistant = 3,
		/obj/item/clothing/under/costume/playbunny/warden = 3,
		/obj/item/clothing/under/costume/playbunny/brig_phys = 3,
		/obj/item/clothing/under/costume/playbunny/prisoner = 3,
		/obj/item/clothing/suit/jacket/playbunny/security_tailcoat = 3,
		/obj/item/clothing/suit/jacket/playbunny/security_tailcoat/assistant = 3,
		/obj/item/clothing/suit/jacket/playbunny/security_tailcoat/warden = 3,
		/obj/item/clothing/suit/toggle/labcoat/playbunny/sec = 3,
		/obj/item/clothing/neck/playbunny/security = 3,
		/obj/item/clothing/neck/playbunny/security_assistant = 3,
		/obj/item/clothing/neck/playbunny/brig_phys = 3,
		/obj/item/clothing/neck/playbunny/prisoner = 3,
		/obj/item/clothing/head/playbunny/security = 3,
		/obj/item/clothing/head/playbunny/security/assistant = 3,
		/obj/item/clothing/head/playbunny/warden = 3,
		/obj/item/clothing/head/playbunny/brig_phys = 3,
		/obj/item/clothing/head/playbunny/prisoner = 3,
		/obj/item/clothing/shoes/fancy_heels/red = 3,
		/obj/item/clothing/shoes/fancy_heels/blue = 3,
		/obj/item/clothing/shoes/fancy_heels/black = 3,
		/obj/item/clothing/shoes/fancy_heels/orange = 3,
	)
