//Marker Signal
#define COMSIG_KB_MSIGNAL_ROTATE_STRUCTURE_DOWN "keybinding_msignal_rotate_structure_down"

//Necromorph
#define COMSIG_KB_NECROMORPH_ABILITY_CHARGE_DOWN "keybinding_necromorph_ability_charge_down"
#define COMSIG_KB_NECROMORPH_ABILITY_DODGE_DOWN "keybinding_necromorph_ability_dodge_down"
#define COMSIG_KB_NECROMORPH_ABILITY_SHOUT_DOWN "keybinding_necromorph_ability_shout_down"
#define COMSIG_KB_NECROMORPH_ABILITY_SCREAM_DOWN "keybinding_necromorph_ability_scream_down"
#define COMSIG_KB_NECROMORPH_ABILITY_SENSE_DOWN "keybind_necromorph_ability_sense_down"
#define COMSIG_KB_NECROMORPH_ABILITY_SNAPSHOT_DOWN "keybinding_necromorph_ability_snapshot_down"
#define COMSIG_KB_NECROMORPH_ABILITY_LONGSHOT_DOWN "keybinding_necromorph_ability_longshot_down"
//placeholder lurker abilities, remove comment when implemented
#define COMSIG_KB_NECROMORPH_ABILITY_TOGGLESHELL_DOWN "keybinding_necromorph_ability_toggleshell_down"
#define COMSIG_KB_NECROMORPH_ABILITY_SPINELAUNCH_DOWN "keybinding_necromorph_ability_spinelaunch_down"
//Leaper
#define COMSIG_KB_NECROMORPH_ABILITY_GALLOP_DOWN "keybinding_necromorph_ability_gallop_down"
#define COMSIG_KB_NECROMORPH_ABILITY_TAILSTAB_DOWN "keybinding_necromorph_ability_tailstab_down"
//Exploder
#define COMSIG_KB_NECROMORPH_ABILITY_EXPLODE_DOWN "keybinding_necromorph_ability_explode_down"
#define COMSIG_KB_NECROMORPH_ABILITY_EXPLODECHARGE_DOWN "keybinding_necromorph_ability_explodecharge_down"
//Hunter & Uber
#define COMSIG_KB_NECROMORPH_ABILITY_HUNTERSWING_DOWN "keybinding_necromorph_ability_hunterswing_down"
#define COMSIG_KB_NECROMORPH_ABILITY_TAUNT_DOWN "keybinding_necromorph_ability_taunt_down"
#define COMSIG_KB_NECROMORPH_ABILITY_REGENERATE_DOWN "keybinding_necromorph_ability_regenerate_down"
#define COMSIG_KB_NECROMORPH_ABILITY_FRENZY_DOWN "keybinding_necromorph_ability_frenzy_down"
//Brute
#define COMSIG_KB_NECROMORPH_ABILITY_SLAM_DOWN "keybinding_necromorph_ability_slam_down"
#define COMSIG_KB_NECROMORPH_ABILITY_CURL_DOWN "keybinding_necromorph_ability_curl_down"
//Twitcher
#define COMSIG_KB_NECROMORPH_ABILITY_STEPSTRIKE_DOWN "keybinding_necromorph_ability_stepstrike_down"
