/obj/machinery/vending/wardrobe/syndie_wardrobe/interdyne
	products = list(
		/obj/item/clothing/glasses/science/ballistic = 3,
		/obj/item/clothing/glasses/hud/health/ballistic = 3,
		/obj/item/clothing/glasses/meson/ballistic = 3,
		/obj/item/clothing/head/bio_hood/interdyne = 3,
		/obj/item/clothing/suit/bio_suit/interdyne = 3,
		/obj/item/clothing/suit/toggle/labcoat/nova/interdyne_labcoat/black = 5,
		/obj/item/clothing/suit/toggle/labcoat/nova/interdyne_labcoat/white = 5,
		/obj/item/clothing/suit/syndicate/interdyne_jacket = 5,
		/obj/item/clothing/head/beret/medical/nova/interdyne = 5,
		/obj/item/clothing/under/syndicate/nova/interdyne/miner = 5,
		/obj/item/clothing/under/syndicate/nova/interdyne = 5,
		/obj/item/clothing/shoes/combat = 5,
		/obj/item/clothing/mask/gas = 5,
		/obj/item/clothing/suit/hooded/wintercoat/medical/viro/interdyne = 5,
		/obj/item/storage/backpack/messenger/interdyne = 5,
		/obj/item/storage/backpack/satchel/interdyne = 5,
		/obj/item/storage/backpack/duffelbag/syndie/interdyne = 5,
		/obj/item/storage/backpack/interdyne = 5,
		/obj/item/clothing/accessory/nova/acc_medal/neckpin/interdyne = 10,
		/obj/item/clothing/suit/toggle/jacket/nova/colorable_bomber/interdyne = 3,
		/obj/item/storage/toolbox/guncase/nova/interdynespec = 3,
		/obj/item/storage/toolbox/guncase/nova/interdyne = 3,
		/obj/item/storage/backpack/industrial/frontier_colonist/satchel = 3,
		/obj/item/storage/backpack/industrial/frontier_colonist/messenger = 3,
		)
