/obj/machinery/vending/clothing
	product_categories_ff = list(
		list(
			"name" = "Special",
			"icon" = "star",
			"products" = list(
				/obj/item/storage/backpack/waistbag = 3,
				/obj/item/storage/backpack/waistbag/camo = 3,
				/obj/item/clothing/neck/bunny/bunnytie = 3,
				/obj/item/clothing/under/costume/playbunny = 3,
				/obj/item/clothing/under/costume/playbunny/british = 3,
				/obj/item/clothing/under/costume/playbunny/communist = 3,
				/obj/item/clothing/under/costume/playbunny/usa = 3,
				/obj/item/clothing/suit/jacket/tailcoat = 3,
				/obj/item/clothing/neck/bunny/bunnytie = 3,
				/obj/item/clothing/neck/bunny/bunnytie/communist = 3,
				/obj/item/clothing/neck/bunny/bunnytie/blue = 3,
				/obj/item/clothing/head/playbunnyears = 3,
				/obj/item/clothing/head/playbunnyears/british = 3,
				/obj/item/clothing/head/playbunnyears/communist = 3,
				/obj/item/clothing/head/playbunnyears/usa = 3,
				/obj/item/clothing/shoes/fancy_heels/cc = 3,
				/obj/item/clothing/shoes/fancy_heels/red = 3,
				/obj/item/clothing/shoes/fancy_heels/blue = 3,
				/obj/item/clothing/shoes/fancy_heels/lightgrey = 3,
				/obj/item/clothing/shoes/fancy_heels/navyblue = 3,
				/obj/item/clothing/shoes/fancy_heels/white = 3,
				/obj/item/clothing/shoes/fancy_heels/darkblue = 3,
				/obj/item/clothing/shoes/fancy_heels/black = 3,
				/obj/item/clothing/shoes/fancy_heels/purple = 3,
				/obj/item/clothing/shoes/fancy_heels/red = 3,
				/obj/item/clothing/shoes/fancy_heels/grey = 3,
				/obj/item/clothing/shoes/fancy_heels/brown = 3,
				/obj/item/clothing/shoes/fancy_heels/orange = 3,
				/obj/item/clothing/shoes/jackboots/gogo_boots = 3,
				/obj/item/clothing/shoes/fancy_heels/lightblue = 3,
				/obj/item/clothing/shoes/galoshes/heeled = 3,
				/obj/item/clothing/shoes/fancy_heels/green = 3,
				/obj/item/clothing/shoes/clown_shoes/heeled = 3,
				/obj/item/clothing/shoes/fancy_heels/darkgreen = 3,
				/obj/item/clothing/shoes/fancy_heels/teal = 3,
				/obj/item/clothing/shoes/fancy_heels/mutedblack = 3,
				/obj/item/clothing/shoes/fancy_heels/mutedblue = 3,
				/obj/item/clothing/shoes/fancy_heels/beige = 3,
				/obj/item/clothing/shoes/fancy_heels/darkgrey = 3,
			),
		),
	)
